# Add configuration values here, as shown below.
#
# pusher_app_id: "2954"
# pusher_key: 7381a978f7dd7f9a1117
# pusher_secret: abdc3b896a0ffb85d373
# stripe_api_key: sk_test_2J0l093xOyW72XUYJHE4Dv2r
# stripe_publishable_key: pk_test_ro9jV5SNwGb1yYlQfzG17LHK
#
# production:
   stripe_api_key: sk_test_bKqUv2fjFwKmq7m5QeL3RI3800ybVTH4Ey
   stripe_publishable_key: pk_test_Z5MdSyNl2YZJvnIeRvrSEL8x00qXGNoDwq


#  :publishable_key => 'YOUR_STRIPE_PUBLISHABLE_KEY',
#  :secret_key => 'YOUR_STRIPE_SECRET_KEY'

# Twilio
  ACCOUNT_SID: ACb9fe11cdfcd5709cd60702f6b8b85fdd
  AUTH_TOKEN: afdad896548636befdcb10428947660c
#secret_key_base: THERE WILL ALREADY BE SOME CRAZY STRING HERE. LEAVE IT THERE.

twilio_account_sid:  ACb9fe11cdfcd5709cd60702f6b8b85fdd
twilio_auth_token:  afdad896548636befdcb10428947660c
twilio_phone_number:  +18326262216'


#gmail
gmail_address: folubode@gmail.com
gmail_password: 


#facebookdeveloper
YOUR_FACEBOOK_ID: 215926375610887
YOUR_FACEBOOK_SECRET: c890fbe946ec6782bb026f0390b949b0
